{
 "title": "Dream Machin Pro",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Check",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "ICMP ping" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "UDM State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 9, "x": 7, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "UDM State" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "UDM Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "UDM Uptime" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "温度",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "Temperature CPU" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Temperature PHY",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "Temperature PHY" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Temperature Local",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "Temperature Local" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / MEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDM Cpu Usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "UDM Cpu Usage %" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "UDM Memory Usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "UDM Memory Usage %" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RX Packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "/Port.*Total RX Packets/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total TX Packets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "/Port.*Total TX Packets/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total RX Dropped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "/Port.*Total RX Dropped/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total TX Dropped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "/Port.*Total TX Dropped/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total RX Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "/Port.*Total RX Errors/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Total TX Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "Network" },
       "host": { "filter": "Dream Machine Pro_VLAN11" },
       "item": { "filter": "/Port.*Total TX Errors/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}