{
 "title": "Proxmox Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": {}
   },
   {
    "name": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Host Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power On/Off",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Proxmox: Node.*pve.*Status/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Host CPU Load Avarage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*CPU, loadavg/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Host CPU, iowait",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*CPU, iowait/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": " pve05 uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Proxmox: Node.*pve.*Uptime/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Proxmox: LXC.*pve.*Uptime/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Proxmox: VM.*pve.*Uptime/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Root filesystem, total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Root filesystem, total/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Root filesystem used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Root filesystem, used/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Swap filesystem, total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Swap filesystem, total/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "Swap filesystem, used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Swap filesystem, used/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*CPU, usage/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "pve05 CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Proxmox: VM.*pve.*CPU usage/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Proxmox: LXC.*pve.*CPU usage/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "pve05 Memory Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Memory, total/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "pve05 Memory Allocation",
     "type": "stat",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve.*Memory total/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: VM.*pve.*Memory total/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Memory, used/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve1.*Memory usage/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "pve05 Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 4 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: VM.*pve.*Memory usage/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve.*Memory usage/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming data, rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Incoming data, rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Incoming data, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "pve05 Incoming data, rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 5 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve.*Incoming data, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: VM.*pve.*Incoming data, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing data, rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Outgoing data, rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: Node.*pve.*Outgoing data, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "pve05 Outgoing data, rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 6 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve.*Outgoing data, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: VM.*pve.*Outgoing data, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk write/read, rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "pve05 Disk write, rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve.*Disk write, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: VM.*pve.*Disk write, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "pve05 Disk read, rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: LXC.*pve.*Disk read, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Group" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Proxmox: VM.*pve.*Disk read, rate/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}