{
 "title": "zabbix proxy status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": {}
   },
   {
    "name": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "queue",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/queue/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Queue/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trend",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Required performance/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Uptime/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Values waiting to be sent",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Values waiting to be sent/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "cache, % used",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/cache, % used/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "internal processes, in %",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/internal processes, in %/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "collector processes, in %",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/collector processes, in %/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of processed ",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Number of processed/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}